version: "3.4"
services:
  db:
    image: mysql:5.7
    container_name: address_book_db
    ports:
      - "3307:3306"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: address_book_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql

  java-app:
    image: nejlasahin/simple-address-book
    container_name: address_book_app
    ports:
      - "8080:8080"
    depends_on:
      - "db"
volumes:
  db: